POST http://localhost:3000/admin/create_admin  HTTP/1.1
Content-Type: application/json 

{
    "institute_name":"CEG",
    "phone_no":"1234567890",
    "current_plan":"1205",
    "plan_expire":"2018-08-12 00:00:00"
}


###


POST http://localhost:3000/admin/create_student  HTTP/1.1
Content-Type: application/json 

{
    "s_name":"dhivastud",
    "section_id":"06a",
    "blood_group":"B+",
    "address":"Chennai",
    "father_name":"mathiyalagan",
    "emis_no":"4655654789",
    "fees":"20000",
    "due":"12000",
    "phone_no_1":"1254689724",
    "phone_no_2":"4567891235",
    "gender":"Male",
    "img":""
}




###

POST http://localhost:3000/admin/update_student  HTTP/1.1
Content-Type: application/json 

{
    "s_id": "1",
    "s_name":"Monisha",
    "section_id":"2",
    "blood_group":"B+",
    "address":"Chennai",
    "father_name":"Adnan",
    "emis_no":"4655654789",
    "fees":"20000",
    "due":"12000",
    "phone_no_1":"1254689724",
    "phone_no_2":"4567891235",
    "gender":"Male",
    "img":""
}

###

POST http://localhost:3000/admin/delete_student  HTTP/1.1
Content-Type: application/json 

{
    "s_id": "3"

}

###


POST http://localhost:3000/admin/create_teacher  HTTP/1.1
Content-Type: application/json 

{   
    "t_name":"Swamy",
    "phone_no":"5456687899",
    "qualification":"M.E. CS",
    "gender":"Female",
    "img":"",
    "designation":"",
    "bank_ac_detail":"",
    "address":"Chennai",
    "salary":"52000"
}


###


POST http://localhost:3000/admin/update_teacher  HTTP/1.1
Content-Type: application/json 

{
    "t_id": "1",
    "t_name":"SOS",
    "phone_no":"5456687899",
    "qualification":"M.E. CS",
    "gender":"Female",
    "img":"",
    "designation":"",
    "bank_ac_detail":"",
    "address":"Chennai",
    "salary":"52000"

}

###


POST http://localhost:3000/admin/delete_teacher  HTTP/1.1
Content-Type: application/json 

{
    "t_id": "1"

}

###

POST http://localhost:3000/admin/create_standard  HTTP/1.1
Content-Type: application/json 

{
     "standard_name": "06",
     "curriculum": "Ennum Ezuthum"
}

###

POST http://localhost:3000/admin/update_standard  HTTP/1.1
Content-Type: application/json 

{ 
     "standard_name":"01",
    "curriculum":"new chngnnnnnnnnnnnnnnug"
}

###

POST http://localhost:3000/admin/delete_standard  HTTP/1.1
Content-Type: application/json 

{
     "standard_name": "01"
     
}


###

POST http://localhost:3000/admin/create_section  HTTP/1.1
Content-Type: application/json 

{
    "section_name":"a",
    //"t_id":"2",
    "standard":"06"
}


###



POST http://localhost:3000/admin/update_section  HTTP/1.1
Content-Type: application/json 

{   "section_id":"4",
    "section_name":"12",
    "t_id":"2",
    "standard":"10th"
}

###



POST http://localhost:3000/admin/delete_section  HTTP/1.1
Content-Type: application/json 

{ 
      "section_id":"4"

}

###


POST http://localhost:3000/admin/create_subject  HTTP/1.1
Content-Type: application/json 

{ 
       //"subject_id":"02",
    "subject_name":"English",
    "standard_name":"03"

}


###


POST http://localhost:3000/admin/update_subject  HTTP/1.1
Content-Type: application/json 

{ 
       "subject_id":"01",
    "subject_name":"Englis",
    "standard_name":"03"

}


###


POST http://localhost:3000/admin/delete_subject  HTTP/1.1
Content-Type: application/json 

{ 
       "subject_id":"02"
    

}
###

POST http://localhost:3000/admin/create_exam  HTTP/1.1
Content-Type: application/json 

{ 
       "e_name":"Mid-term",
    "standard_name":"03",
    "subjects":"Eng03",
    "e_date":"2018-05-12",
    "acad_year":"2021"
    

}
###

POST http://localhost:3000/admin/update_exam  HTTP/1.1
Content-Type: application/json 

{ 
       "e_id":"1",
       "e_name":"Mid-term",
    "standard":"12th",
    "subjects":"Science",
    "e_date":"2018-05-12 00:00:00",
    "acad_year":"2021"
    

}


###

POST http://localhost:3000/admin/delete_exam  HTTP/1.1
Content-Type: application/json 

{
    "e_id":"1"
}


###

POST http://localhost:3000/admin/create_subjectstaff HTTP/1.1
Content-Type: application/json 

{
    "subject_id":"2",
    "teacher_id":"1",
    "section_id":"1"
}



###

POST http://localhost:3000/admin/update_subjectstaff HTTP/1.1
Content-Type: application/json 

{
    
    "subject_id":"2",
    "teacher_id":"1",
    "section_id":"1"
}

###


POST http://localhost:3000/admin/view_personal  HTTP/1.1
Content-Type: application/json 

{
    "admin_id":"1"
}


###


POST http://localhost:3000/admin/view_section  HTTP/1.1
Content-Type: application/json 

{
    "admin_id":"1"
}



###


POST http://localhost:3000/admin/view_student  HTTP/1.1
Content-Type: application/json 

{
    "admin_id":"1"
}


###


POST http://localhost:3000/admin/view_teacher  HTTP/1.1
Content-Type: application/json 

{
    "admin_id":"1"
}


###


POST http://localhost:3000/admin/view_exam  HTTP/1.1
Content-Type: application/json 

{
    "admin_id":"1"
}

###